In [45]:
import numpy as np

In [54]:
myar=np.array([1,2,3,4,5,6,7,8,9,10])

In [56]:
print(myar[0])

1


In [131]:
two_di=np.array([[1,2,3,4],[9,8,7,6],[5,10,11,12]])
two_di=np.reshape(two_di,12)
print(two_di,"\n")
two_di=np.reshape(two_di,(3,4))
print(two_di,"\n")
print("Value at two_di[1][3]",two_di[1][3])


[ 1  2  3  4  9  8  7  6  5 10 11 12] 

[[ 1  2  3  4]
 [ 9  8  7  6]
 [ 5 10 11 12]] 

Value at [1][3] 6


In [137]:
three_di=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print(three_di)
print("\nValue at three_di[1][3][3]",three_di[1][2][3])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Value at three_di[1][3][3] 24
